# Generated by Django 3.1 on 2020-11-06 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('seats', models.IntegerField(default=0)),
                ('discription', models.TextField(blank=True, null=True, verbose_name='About the event')),
                ('time_start', models.DateTimeField(verbose_name='Time of starting of event')),
                ('time_end', models.DateTimeField(verbose_name='Time of ending of event')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=3, verbose_name='Country')),
            ],
        ),
    ]
