# Generated by Django 3.1 on 2020-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
    ]
